spring:
  cloud:
    gateway:
      routes:
        - id: ribbon_client
          predicates:
            - Path=/gateway/**
          filters:
             - StripPrefix=1
          uri: http://localhost:8082/

        - id: cookie_route
          predicates:
            - Cookie=name,huzhanglin
          uri: https://www.baidu.com/?tn=02003390_82_hao_pg

        - id: auth_route
          predicates:
            - Path=/auth/**
            - Auth=authorization,1234
          uri: https://www.baidu.com/?tn=02003390_82_hao_pg

          #跨域设置
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
            exposedHeaders: "Content-Disposition,Content-Type,Cache-Control"
