# 本地服务访问
server:
  # 服务端口
  port: 8770
  # 服务IP
  address: 0.0.0.0

spring:
  application:
    # 应用服务名
    name: dynamic-manage
  profiles:
    active: db,mail
  cloud:
    loadbalancer:
      ribbon:
        # 升级版本后，已包启BlockingLoadBalancerClient负载均衡客户端（spring-cloud-loadbalancer），不启用ribbon负载均衡服务
        enabled: false
    # 注册到nacos，服务注册发现和配置管理中心
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone:  http://192.168.56.100:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id:  ${spring.cloud.client.ip-address}:${server.port}

# 启用服务健康检测，注册中心将通过http://host:port/actuator/health 检测服务的存活，默认10s一次
management:
  endpoints:
    web:
      exposure:
        include:
        # 开放所有端点health，info，metrics，通过actuator/+端点名就可以获取相应的信息。默认打开health和info
        - "*"
  health:
    mail:
      # 不开启mail健康检查
      enabled: false
    # 开启后打印详细信息
    show-details: always
    refresh:
      enabled: true

# 配置日志
logging:
  level:
    com.netflix: info
    org.springframework.boot: info
    # log 级别
    org.springframework.cloud.gateway: debug
#  config: classpath:log4j2.xml


# 配置授权访问服务的IP
system:
  auth:
    ip: 127.0.*,192.168.56.*,0.*

# 是否启用springboot的debug调试模式，会打印详细日志信息
debug: true